In [1]:
import numba as nb
import numpy as np
from pprint import pp as print
from utils import timer

In [2]:
def gen_data_vectors(n):
    """
    Enumerate all possible combinations of the values between 0 and n-1 
    to use when calculating the sum of 3 squares
    
    Note: 
    Total output items = n**3
    At n=1000, 7 GBs of data is created - this grows exponentially
    """
    n_items=np.arange(n)
    return np.array(np.meshgrid(n_items,n_items,n_items)).reshape(3,-1)

In [3]:
data_vectors=gen_data_vectors(2)
print(data_vectors)

array([[0, 0, 1, 1, 0, 0, 1, 1],
       [0, 0, 0, 0, 1, 1, 1, 1],
       [0, 1, 0, 1, 0, 1, 0, 1]])


In [4]:
@nb.vectorize(['int64(int64,int64,int64)'])
def nb_sum3sqares(a,b,c):
    return a**3+b**3+c**3

In [5]:
timer.start()
print(nb_sum3sqares(*data_vectors))
timer.end()

array([0, 1, 1, 2, 1, 2, 2, 3])


'Total Process Time: 0.0002 (seconds)'

In [6]:
@nb.vectorize(['int64(int64,int64,int64)'], target='parallel')
def nb_mp_sum3sqares(a,b,c):
    return a**3+b**3+c**3

In [7]:
timer.start()
print(nb_mp_sum3sqares(*data_vectors))
timer.end()

array([0, 1, 1, 2, 1, 2, 2, 3])


'Total Process Time: 0.0113 (seconds)'

In [8]:
data_vectors_med=gen_data_vectors(250)
data_vectors_lg=gen_data_vectors(1000)

In [9]:
timer.start()
nb_mp_sum3sqares(*data_vectors_med)
timer.end()

'Total Process Time: 0.0169 (seconds)'

In [10]:
timer.start()
nb_mp_sum3sqares(*data_vectors_lg)
timer.end()

'Total Process Time: 0.7853 (seconds)'